CREATE TABLE IF NOT EXISTS agents (
    agent_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent_name TEXT NOT NULL,
    team TEXT NOT NULL CHECK (team IN ('Platform', 'Network', 'Applications', 'Billing', 'Security')),
    shift TEXT NOT NULL CHECK (shift IN ('Morning', 'Evening', 'Night')),
    experience_level TEXT NOT NULL CHECK (experience_level IN ('Junior', 'Mid', 'Senior', 'Lead')),
    active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS categories (
    category_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_name TEXT NOT NULL,
    subcategory TEXT NOT NULL,
    sla_hours NUMERIC(6,2) NOT NULL CHECK (sla_hours > 0),
    UNIQUE (category_name, subcategory)
);

CREATE TABLE IF NOT EXISTS tickets (
    ticket_id TEXT PRIMARY KEY,
    category_id INTEGER NOT NULL REFERENCES categories(category_id),
    agent_id INTEGER REFERENCES agents(agent_id),
    priority TEXT NOT NULL CHECK (priority IN ('P1', 'P2', 'P3', 'P4')),
    status TEXT NOT NULL CHECK (status IN ('Open', 'In Progress', 'Resolved', 'Escalated', 'Closed')),
    created_at TIMESTAMPTZ NOT NULL,
    first_response_at TIMESTAMPTZ,
    resolved_at TIMESTAMPTZ,
    root_cause TEXT,
    resolution_type TEXT CHECK (resolution_type IN ('Config Change', 'Code Fix', 'Knowledge Base', 'Vendor Fix', 'Restart', 'User Education', 'Monitoring Update', 'Duplicate', 'Unresolved')),
    escalation_flag BOOLEAN NOT NULL DEFAULT FALSE,
    customer_impact TEXT NOT NULL CHECK (customer_impact IN ('None', 'Low', 'Medium', 'High', 'Critical')),
    description TEXT NOT NULL,
    inserted_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CHECK (first_response_at IS NULL OR first_response_at >= created_at),
    CHECK (resolved_at IS NULL OR resolved_at >= created_at)
);

CREATE OR REPLACE VIEW ticket_metrics AS
SELECT
    t.ticket_id,
    t.category_id,
    c.category_name,
    c.subcategory,
    c.sla_hours,
    t.agent_id,
    a.agent_name,
    a.team,
    a.shift,
    a.experience_level,
    t.priority,
    t.status,
    t.created_at,
    t.first_response_at,
    t.resolved_at,
    t.root_cause,
    t.resolution_type,
    t.escalation_flag,
    t.customer_impact,
    t.description,
    EXTRACT(EPOCH FROM (t.resolved_at - t.created_at)) / 3600.0 AS resolution_hours,
    EXTRACT(EPOCH FROM (t.first_response_at - t.created_at)) / 3600.0 AS first_response_hours,
    EXTRACT(EPOCH FROM (COALESCE(t.resolved_at, NOW()) - t.created_at)) / 3600.0 AS hours_open,
    CASE
        WHEN COALESCE(t.resolved_at, NOW()) > t.created_at + (c.sla_hours || ' hours')::INTERVAL THEN TRUE
        ELSE FALSE
    END AS sla_breached
FROM tickets t
JOIN categories c ON c.category_id = t.category_id
LEFT JOIN agents a ON a.agent_id = t.agent_id;

